name: Ubuntu Packaging

on:
  release:
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      env: 
        DEBIAN_FRONTEND: "noninteractive"
    - name: Prepare Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y pbuilder ubuntu-dev-tools debhelper
    - name: Build Package
      run: debuild-pbuilder
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: *.deb
        path: ..
          
